### ISSUE TITLE
Release and maintain release 1312 (23Q4)

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2155]
# Epic: Release and maintain release 1312 (23Q4)

## Scope

As Garden Linux adopter, I want new release, including latest version of the packages I need. 

## Support schedule

| Initial release                                  | 2023-11-16 | 
| :---                                                   | :--- |
| End of standard support               | 2024-05-16 | 
| End of Long Term Support (LTS)  | 2024-08-16 | 

## Releases
- [x] Release [1312.7](https://github.com/gardenlinux/gardenlinux/releases/tag/1312.7) (2024-07-04)
- [x] Release 1312.6 (skipped)
- [x] Release [1312.5](https://github.com/gardenlinux/gardenlinux/releases/tag/1312.5) (2024-06-13)
- [x] Release 1312.4 (skipped)
- [x] Release [1312.3](https://github.com/gardenlinux/gardenlinux/releases/tag/1312.3) (2024-02-14)
- [x] Release [1312.2](https://github.com/gardenlinux/gardenlinux/releases/tag/1312.2) (2024-01-15)
- [x] Release [1312.1](https://github.com/gardenlinux/gardenlinux/releases/tag/1312.1) (2023-11-23)
- [x] Release [1312.0](https://github.com/gardenlinux/gardenlinux/releases/tag/1312.0) (2023-11-16)

### August

- https://github.com/gardenlinux/gardenlinux/issues/2233

### July 
- https://github.com/gardenlinux/gardenlinux/issues/2189

### June
- https://github.com/gardenlinux/process/issues/98
- https://github.com/gardenlinux/gardenlinux/issues/2164
