### ISSUE TITLE
Release 1443 patch 8 with latest security changes

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2163]
## Summary 

Publish patch 8 for 1443 release, that addresses latest high and critical severity security findings. 
The patch must include latest published golang, containerd patches. 
The patch should include, if feasible latest kernel patch. 

**Tasks:**

- [x] @Vincinator to build kernel [6.6.35](https://github.com/gardenlinux/package-linux/releases/tag/6.6.35-0gardenlinux1%2Bbp1443)
- [x] @fwilhe to build latest golang 1.22.5 , containerd 1.6.24 packages.
- [x] @fwilhe to complete stage 1 of the build process.
- [x] @fwilhe to complete stage2 of the build process.
- [x] @fwilhe to publish the release note including information about the fixes included  (package from - to information + venerability references).
- [x] @pnpavlov to inform @MrBatschner that the patch is ready for consumption.

**Comment by Vincinator** [comment]
https://github.com/gardenlinux/package-linux/releases/tag/6.6.35-0gardenlinux1%2Bbp1443

latest 6.6 kernel package are available now.

**Comment by Akendo** [comment]
@Akendo add the list of CVE's so we can compose the changelog.

**Comment by Akendo** [comment]
> WE have two vulnerabilities we had to fix affecting `golang`:
> 
>     * [CVE-2024-24789](https://github.com/advisories/GHSA-236w-p7wf-5ph8)
> 
>     * [CVE-2024-24790](https://github.com/advisories/GHSA-49gw-vxvf-fc2g)
> 
> 
> Hence, the release fixes these now.

**Comment by pnpavlov** [comment]
Patch done, release note updated, @MrBatschner  informed.
