### ISSUE TITLE
Release 1312 patch 6 with latest security changes

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2164]
## Summary 

Release new 1312 release patch that addresses latest high and critical severity security findings.  The patch should include latest published kernel patch. The number should be included in the release note, together with a summary of the vulnerabilities addressed.

**Tasks:**

- [x] @Akendo confirm only kernel needs to be included, but no golang & containerd.
- [x] @Akendo Support in creating IAM profile. 
- [x] @Vincinator build latest 6.1 kernel package
- [x] @Vincinator build latest golang and rebuild  containerd, dockerd, runc.
- [x] @fwilhe complete stage 1 of the build process.
- [ ] @fwilhe complete stage2 of the build process.
- [ ] @fwilhe publish the release note including information about the fixes included  (package from - to information + venerability references).
- [ ] @pnpavlov inform @MrBatschner that the patch is ready for consumption.

**Comment by Vincinator** [comment]
6.1.95 conflicts with intel fpga drivers. 

I started the [update-dfl.sh](https://gitlab.com/gardenlinux/gardenlinux-package-linux-6.1/-/blob/main/update-dfl.sh?ref_type=heads) script locally

**Comment by Vincinator** [comment]
previous step is done, now running [prepare-source](https://gitlab.com/gardenlinux/gardenlinux-package-linux-6.1/-/blob/main/prepare-source?ref_type=heads) script to check patch compatibility, or if I need to fix patches.

**Comment by Akendo** [comment]
@Akendo add the list of CVE's so we can compose the changelog.

**Comment by Akendo** [comment]
WE have two vulnerabilities we had to fix affecting golang:
- CVE-2024-24789 
- CVE-2024-24790

Hence, the release fixes these now.

**Comment by Akendo** [comment]
I've checked the rootfs and see that we have to update the Golang packages as well. Since we're affect. Also, we have docker still present that needs to be updated too. Hence, we need to upgrade Golang for 1312 as well.
```
bin/containerd (gobinary)

Total: 8 (UNKNOWN: 0, LOW: 0, MEDIUM: 6, HIGH: 1, CRITICAL: 1)

┌─────────┬────────────────┬──────────┬────────┬───────────────────┬─────────────────┬──────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │  Fixed Version  │                            Title                             │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼─────────────────┼──────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-24790 │ CRITICAL │ fixed  │ 1.21.5            │ 1.21.11, 1.22.4 │ golang: net/netip: Unexpected behavior from Is methods for   │
│         │                │          │        │                   │                 │ IPv4-mapped IPv6 addresses                                   │
│         │                │          │        │                   │                 │ https://avd.aquasec.com/nvd/cve-2024-24790                   │
│         ├────────────────┼──────────┤        │                   ├─────────────────┼──────────────────────────────────────────────────────────────┤
│         │ CVE-2023-45288 │ HIGH     │        │                   │ 1.21.9, 1.22.2  │ golang: net/http, x/net/http2: unlimited number of           │
│         │                │          │        │                   │                 │ CONTINUATION frames causes DoS                               │
│         │                │          │        │                   │                 │ https://avd.aquasec.com/nvd/cve-2023-45288                   │
│         ├────────────────┼──────────┤        │                   ├─────────────────┼──────────────────────────────────────────────────────────────┤

**Comment by pnpavlov** [comment]
Relevant changes:
- https://github.com/gardenlinux/glci/pull/85

**Comment by Vincinator** [comment]
#2189

**Comment by pnpavlov** [comment]
We will publish directly patch 7 and skip 6
