### ISSUE TITLE
Manage cloud infrastructure inventory

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2176]
# Epic: Manage cloud infrastructure inventory
 
## Summary 
As Garden Linux team member and contributor, I want to have an overview of the cloud accounts available and their usage model. The information should contain details about what I can do with the account and who is the owner/contact person in case I'm not sure.

## Requirements
The inventory should be up-to-date and easy to maintain. It should contain:
- Cloud provider name.
- Account / Subscription / Project id and name.
- Account owner / point of contact.
- Usage - sandbox / development / quality / production.
- Additional information that is important to take in account before using (e.g. quota or access restrictions).

## Definition of done
- [ ] There is an inventory in easy to maintain commonly used format (excel, markdown, other) in a location that has access control (e.g. private repository or MS Teams/Private channel).
- [ ] The list is complete and up-todate. Aligned with infrastructure team and account owners informed.
- [ ] The information about the accounts, how to use, how to maintain the inventory is documented and communicated to the team.

## Tasks

- #2175

**Comment by Vincinator** [comment]
Here are some starting points:
- https://github.com/gardenlinux/gardenlinux-backlog/blob/main/hyperscaler-accounts.md
- https://github.tools.sap/gardenlinux/infrastructure

**Comment by sramapu** [comment]
Denis works on a new issue, so closing this.
