### ISSUE TITLE
Release 1312 patch 8 - skipped

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2233]
# Release 1312 patch 8

## Summary 

Release new 1312 release patch that addresses latest high and critical severity security findings.  The patch should include latest published kernel patch. The number should be included in the release note, together with a summary of the vulnerabilities addressed.

## Tasks
- [ ] Identify packages that must be patched
- [ ] Complete the build (stage 1)
- [ ] Complete the publishing (stage 2)
- [ ] Publish the release note
- [ ] Inform Gardener team the patch is ready.

**Comment by pnpavlov** [comment]
Patch 8 will not be produced. Release is considered out of maintanenance as of 16th Aug 2024 and the recommended approach is to upgrade to the latest supported patch of the latest supported release in standard support.
