### ISSUE TITLE
Release 1443 patch 12

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2234]
# Release 1443 patch 12

## Summary 

Release new 1443 release patch that addresses latest high and critical severity security findings.  The patch should include latest published kernel patch. The number should be included in the release note, together with a summary of the vulnerabilities addressed.

## Changes 
- https://github.com/gardenlinux/gardenlinux/issues/2262

## Tasks
- [x] Identify packages that must be patched
 - openssl 3.1.5 → 3.1.7
 - krb5 1.20.1 → 1.20.2
 - libpcap 1.10.4 → 1.10.5
 - linux 6.6.41 → 6.6.54
 - openssh 9.6p1 → 9.8p1
 - python3 3.11.6 → 3.11.9-1gardenlinux0
 - libxml2 2.9.14 → 2.9.14-gl0
 - bind9 9.19.21 → 9.19.24
- [ ] Complete the build (stage 1)
- [ ] Complete the publishing (stage 2)
- [ ] Publish the release note
- [ ] Inform Gardener team the patch is ready.

**Comment by MrBatschner** [comment]
Regarding https://github.com/gardenlinux/gardenlinux/issues/2262: already cherry-picked in https://github.com/gardenlinux/gardenlinux/commit/9f5384a52ada8389726a4282b0c56c09c63b1442

**Comment by fwilhe** [comment]
https://github.com/gardenlinux/gardenlinux/releases/tag/1443.15

skipped a few version numbers because of issues when creating the repo.

**Comment by fwilhe** [comment]
@gardenlinux/gardener-skipper-operating-system fyi

**Comment by MrBatschner** [comment]
> @gardenlinux/gardener-skipper-operating-system fyi

Will take care.
