### ISSUE TITLE
Create 1592 patch 1

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2273]
# Create 1592 patch 1

## Summary 

Release new 1443 release patch that addresses latest high and critical severity security findings.  The patch should include latest published kernel patch. The number should be included in the release note, together with a summary of the vulnerabilities addressed.

## Changed packages

- Linux Kernel [from 6.6.44-0gardenlinux0 to 6.6.47-0gardenlinux0](https://github.com/gardenlinux/repo/commit/37ff2996d237a080c4902737e85ec93bf90d522a)
- libxml2 [from to 2 2.12.7+dfsg-3gardenlinux0](https://github.com/gardenlinux/repo/commit/5be9ccd033e3ad2e3aa0f6c2234603835eb3dfa8)

## Fixes
- https://github.com/gardenlinux/gardenlinux/issues/2262
- https://github.com/gardenlinux/gardenlinux/issues/2278
- https://github.com/gardenlinux/gardenlinux/issues/2265
- 

## Tasks
- [x] Identify packages that must be patched
  - [x] kernel 6.6.47
  - [x] libxml2 2.12.7
- [ ] Complete the build (stage 1)
- [ ] Complete the publishing (stage 2)
- [ ] Publish the release note
- [ ] Inform Gardener team the patch is ready.

**Comment by MrBatschner** [comment]
Regarding https://github.com/gardenlinux/gardenlinux/issues/2262: already cherry-picked in https://github.com/gardenlinux/gardenlinux/commit/1a3c495d4e749b70b9acf880cdc787f3f1cb32c8

**Comment by pnpavlov** [comment]
Package changes:
- [Bump kernel to 6.6.47-0gardenlinux0](https://github.com/gardenlinux/repo/commit/37ff2996d237a080c4902737e85ec93bf90d522a)
- [Bump libxml2 to 2.12.7](https://github.com/gardenlinux/repo/commit/5be9ccd033e3ad2e3aa0f6c2234603835eb3dfa8)
- [Bump python3 to 3.12.4-3](https://github.com/gardenlinux/repo/commit/bc34c09080e8e7a9b573a1a779cd47e4e1891fe0)

**Comment by fwilhe** [comment]
clarify: this is about 1592.1, not 1443.11 @pnpavlov 

<img width="767" alt="Screenshot 2024-08-22 at 13 53 22" src="https://github.com/user-attachments/assets/73a58907-8584-4a85-ae8f-d359599f468f">

**Comment by pnpavlov** [comment]
good catch thanks!

**Comment by fwilhe** [comment]
Done https://github.com/gardenlinux/gardenlinux/releases/tag/1592.1
