### ISSUE TITLE
Create 1592 patch 2

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2320]
# Create 1592 patch 1

## Summary 

Release new 1443 release patch that addresses latest high and critical severity security findings.  The patch should include latest published kernel patch. The number should be included in the release note, together with a summary of the vulnerabilities addressed.

## Changed packages

- todo

## Fixes
- todo

## Tasks
- [ ] Identify packages that must be patched
  - [ ] kernel  
- [ ] Complete the build (stage 1)
- [ ] Complete the publishing (stage 2)
- [ ] Publish the release note
- [ ] Inform Gardener team the patch is ready.
