### ISSUE TITLE
Release and maintain 1877 (25H1)

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2358]
# Epic: Release and maintain 1877 (25H1)

## Scope

- Secureboot
- In-place updates with reboot
- OCI registry support
- New publishing process
- iscsi & nvme support

## Support schedule

| Start of standard maintenance  | 2025-05-21 | 
| :---                                                 | :---               |
| Start of extended maintenance   | 2025-11-21 | 
| Start of LTS maintenance   | 2026-11-21 | 
| End of maintenance                     | 2028-07-31 |  

Definition of the stable releases phases is available in [here](https://github.com/gardenlinux/gardenlinux/blob/main/docs/00_introduction/release.md#stable-releases).

# Releases
- [ ] Release [1877.24](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.24) (2026-09-14 tentative)
- [x] Release [1877.23](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.23) (2026-09-20)
- [x] Release [1877.22](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.22) (2026-08-18)
- [x] Release [1877.21](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.21) (2026-08-11)
- [x] Release [1877.20](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.20) (2026-07-07)
- [x] Release [1877.19](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.19) (2026-05-27)
- [x] Release 1877.18 (skipped)
- [x] Release [1877.17](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.17) (2026-05-09)
- [x] Release [1877.16](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.16) (2026-05-01)
- [x] Release [1877.15](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.15) (2026-04-30)
- [x] Release [1877.14](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.14) (2026-03-26)
- [x] Release [1877.13](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.13) (2026-02-19)
- [x] Release 1877.12 (skipped)
- [x] Release 1877.11 (skipped)
- [x] Release [1877.10](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.10) (2026-01-29)
- [x] Release [1877.9](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.9) (2025-12-30)
- [x] Release [1877.8](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.8) (2025-12-04)
- [x] Release [1877.7](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.7) (2025-11-25)
- [x] Release [1877.6](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.6) (2025-11-04)
- [x] Release [1877.5](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.5) (2025-10-17)
- [x] Release [1877.4](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.4) (2025-09-22)
- [x] Release [1877.3](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.3) (2025-09-09)
- [x] Release [1877.2](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.2) (2025-08-07)
- [x] Release [1877.1](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.1) (2025-07-11)
- [x] Release [1877.0](https://github.com/gardenlinux/gardenlinux/releases/tag/1877.0) (2025-05-21)
   - **Important:** gVisor limitation: not supported, because of gVisor issues.

### Sep 2026
- https://github.com/gardenlinux/gardenlinux/issues/5166

### Aug 2026
- https://github.com/gardenlinux/gardenlinux/issues/5217
- https://github.com/gardenlinux/gardenlinux/issues/5154
- https://github.com/gardenlinux/gardenlinux/issues/4959

### Jul 2026
- https://github.com/gardenlinux/gardenlinux/issues/4900

### May 2026
- https://github.com/gardenlinux/gardenlinux/issues/4769
- https://github.com/gardenlinux/gardenlinux/issues/4755
- https://github.com/gardenlinux/gardenlinux/issues/4611

### Apr 2026
- https://github.com/gardenlinux/gardenlinux/issues/4421

### Mar 2026
- https://github.com/gardenlinux/gardenlinux/issues/4348

### Feb 2026
- https://github.com/gardenlinux/gardenlinux/issues/4239

### Jan 2026
- https://github.com/gardenlinux/gardenlinux/issues/4139

### Dec 2025
- https://github.com/gardenlinux/gardenlinux/issues/3976
- https://github.com/gardenlinux/gardenlinux/issues/3855

### Nov 2025
- https://github.com/gardenlinux/gardenlinux/issues/3544 
- https://github.com/gardenlinux/gardenlinux/issues/3402

### Oct 2025 
- https://github.com/gardenlinux/gardenlinux/issues/3401

### Sept 2025
- https://github.com/gardenlinux/gardenlinux/issues/3349
- https://github.com/gardenlinux/gardenlinux/issues/3240

### Aug 2025 
- https://github.com/gardenlinux/gardenlinux/issues/3197

### June 2025 
- https://github.com/gardenlinux/gardenlinux/issues/3036

### May 2025
- https://github.com/gardenlinux/gardenlinux/issues/2359
