### ISSUE TITLE
Release 1443 patch 13

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2399]
# Release 1443 patch 13

## Summary 

Release new 1443 release patch that addresses latest high and critical severity security findings.  The patch should include latest published kernel patch. The number should be included in the release note, together with a summary of the vulnerabilities addressed.

## Changes 
List GitHub Issues, Pull Requests or other references to important changes for the consumers.
- todo

## Tasks
- [ ] Identify packages that must be patched
  - [ ] linux 6.6.54 → 6.6.tbd
- [ ] Complete the build (stage 1)
- [ ] Complete the publishing (stage 2)
- [ ] Publish the release note
- [ ] Inform Gardener team the patch is ready.

**Comment by pnpavlov** [comment]
path 15 released
