### ISSUE TITLE
Create 1592 patch 3

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2400]
# Create 1592 patch 3

## Summary 

Publish new patch for 1592 release that addresses latest high and critical severity security findings. The patch should include latest published kernel patch. The number should be included in the release note, together with a summary of the vulnerabilities addressed.

## Changed packages
List GitHub Issues, Pull Requests or other references to important changes for the consumers.
- todo

## Fixes
- todo

## Tasks
- [ ] Identify packages that must be patched
   - [ ] linux 6.6.54 → 6.6.60
- [ ] Complete the build (stage 1)
- [ ] Complete the publishing (stage 2)
- [ ] Publish the release note
- [ ] Inform Gardener team the patch is ready.

**Comment by Akendo** [comment]
We need only to fix the libxml2 to fix CVE-2024-40896 @gehoern

**Comment by fwilhe** [comment]
Also take note of this @gehoern @yeoldegrove https://github.com/gardenlinux/gardenlinux/issues/2445
