### ISSUE TITLE
Release 1443 patch 16

### ISSUE THREAD

**Issue by pnpavlov** [gardenlinux/gardenlinux#2478]
# Release 1443 patch 16

## Summary 

Release new 1443 release patch that addresses the latest high and critical severity security findings.  The patch should include the latest published kernel patch. The number should be included in the release note, together with a summary of the vulnerabilities addressed.

## Changes 
List GitHub Issues, Pull Requests or other references to important changes for the consumers.

## Tasks
- [ ] patch to
   - [ ] linux `6.6.54` → `6.6.63`
     - [ ] CVE-2024-50166
     - [ ] CVE-2024-35963
     - [ ] CVE-2024-50084
     - [ ] CVE-2024-50083
     - [ ] CVE-2024-49985
     - [ ] CVE-2024-50095
     - [ ] CVE-2024-50024
     - [ ] CVE-2024-49883
     - [ ] CVE-2024-50237
     - [ ] CVE-2024-26876
     - [ ] CVE-2024-50301
     - [ ] CVE-2024-49983
     - [ ] CVE-2024-50195
     - [ ] CVE-2024-50191
     - [ ] CVE-2024-50064
     - [ ] CVE-2024-49913
     - [ ] CVE-2024-50012
     - [ ] CVE-2024-50300
     - [ ] CVE-2024-50143
     - [ ] CVE-2024-50258
     - [ ] CVE-2024-50078
     - [ ] CVE-2024-50183
     - [ ] CVE-2024-50136
     - [ ] CVE-2024-49952
     - [ ] CVE-2024-50242
     - [ ] CVE-2024-50193
     - [ ] CVE-2024-50232
     - [ ] CVE-2024-50208
     - [ ] CVE-2024-35964
     - [ ] CVE-2024-53076
     - [ ] CVE-2024-49988
     - [ ] CVE-2024-41080
     - [ ] CVE-2024-53081
     - [ ] CVE-2024-50187
     - [ ] CVE-2024-53104
     - [ ] CVE-2024-50151
     - [ ] CVE-2024-50045
     - [ ] CVE-2024-50002
     - [ ] CVE-2024-50233
     - [ ] CVE-2024-27072
     - [ ] CVE-2024-50112
     - [ ] CVE-2024-26836
     - [ ] CVE-2024-50019
     - [ ] CVE-2024-50265
     - [ ] CVE-2024-50046
     - [ ] CVE-2024-50243
     - [ ] CVE-2024-50167
     - [ ] CVE-2024-53099
     - [ ] CVE-2024-53043
     - [ ] CVE-2024-50148
     - [ ] CVE-2024-49879
     - [ ] CVE-2024-50029
     - [ ] CVE-2024-50259
     - [ ] CVE-2024-49944
     - [ ] CVE-2024-49977
     - [ ] CVE-2024-50276
     - [ ] CVE-2024-50036
     - [ ] CVE-2024-49924
     - [ ] CVE-2024-50257
     - [ ] CVE-2024-50236
     - [ ] CVE-2024-50039
     - [ ] CVE-2024-50280
     - [ ] CVE-2024-50059
     - [ ] CVE-2024-50158
     - [ ] CVE-2024-50077
     - [ ] CVE-2024-50086
     - [ ] CVE-2024-50159
     - [ ] CVE-2024-50126
     - [ ] CVE-2024-50189
     - [ ] CVE-2024-50089
     - [ ] CVE-2024-53091
     - [ ] CVE-2024-49929
     - [ ] CVE-2024-50160
     - [ ] CVE-2024-49900
     - [ ] CVE-2024-50035
     - [ ] CVE-2024-49884
     - [ ] CVE-2024-49958
     - [ ] CVE-2024-50111
     - [ ] CVE-2024-50007
     - [ ] CVE-2024-50074
     - [ ] CVE-2024-50201
     - [ ] CVE-2024-50218
     - [ ] CVE-2024-43911
     - [ ] CVE-2024-50154
     - [ ] CVE-2024-53102
     - [ ] CVE-2024-50128
     - [ ] CVE-2024-50180
     - [ ] CVE-2024-50147
     - [ ] CVE-2024-50172
     - [ ] CVE-2024-49938
     - [ ] CVE-2024-50082
     - [ ] CVE-2024-50085
     - [ ] CVE-2024-49903
     - [ ] CVE-2024-50302
     - [ ] CVE-2024-49864
     - [ ] CVE-2024-50231
     - [ ] CVE-2024-49962
     - [ ] CVE-2024-53061
     - [ ] CVE-2024-50278
     - [ ] CVE-2024-53082
     - [ ] CVE-2024-49951
     - [ ] CVE-2024-53096
     - [ ] CVE-2024-49894
     - [ ] CVE-2024-49892
     - [ ] CVE-2024-50047
     - [ ] CVE-2024-50209
     - [ ] CVE-2024-49896
     - [ ] CVE-2024-50287
     - [ ] CVE-2024-49963
     - [ ] CVE-2024-36936
     - [ ] CVE-2024-50290
     - [ ] CVE-2024-26972
     - [ ] CVE-2024-49907
     - [ ] CVE-2024-49874
     - [ ] CVE-2024-50124
     - [ ] CVE-2024-50226
     - [ ] CVE-2024-27011
     - [ ] CVE-2024-49950
     - [ ] CVE-2024-50116
     - [ ] CVE-2024-50057
     - [ ] CVE-2024-50262
     - [ ] CVE-2024-36478
     - [ ] CVE-2024-50117
     - [ ] CVE-2024-49982
     - [ ] CVE-2024-50069
     - [ ] CVE-2024-49989
     - [ ] CVE-2024-50196
     - [ ] CVE-2024-49912
     - [ ] CVE-2024-49946
     - [ ] CVE-2024-50080
     - [ ] CVE-2024-50072
     - [ ] CVE-2024-50027
     - [ ] CVE-2024-53103
     - [ ] CVE-2024-50198
     - [ ] CVE-2024-49967
     - [ ] CVE-2024-50181
     - [ ] CVE-2024-50065
     - [ ] CVE-2024-49886
     - [ ] CVE-2024-50199
     - [ ] CVE-2024-50163
     - [ ] CVE-2024-53088
     - [ ] CVE-2024-50026
     - [ ] CVE-2024-50067
     - [ ] CVE-2024-49882
     - [ ] CVE-2024-50223
     - [ ] CVE-2024-35965
     - [ ] CVE-2024-50032
     - [ ] CVE-2024-53046
     - [ ] CVE-2024-50224
     - [ ] CVE-2024-49980
     - [ ] CVE-2024-50175
     - [ ] CVE-2024-50222
     - [ ] CVE-2024-49868
     - [ ] CVE-2024-53047
     - [ ] CVE-2024-49991
     - [ ] CVE-2024-50295
     - [ ] CVE-2024-50162
     - [ ] CVE-2024-50155
     - [ ] CVE-2024-49866
     - [ ] CVE-2024-49953
     - [ ] CVE-2024-50001
     - [ ] CVE-2024-53095
     - [ ] CVE-2024-50135
     - [ ] CVE-2024-50060
     - [ ] CVE-2024-49875
     - [ ] CVE-2024-50211
     - [ ] CVE-2024-50023
     - [ ] CVE-2024-50248
     - [ ] CVE-2024-50185
     - [ ] CVE-2024-50282
     - [ ] CVE-2024-50022
     - [ ] CVE-2024-50093
     - [ ] CVE-2024-49981
     - [ ] CVE-2024-53057
     - [ ] CVE-2024-50142
     - [ ] CVE-2024-49902
     - [ ] CVE-2024-50063
     - [ ] CVE-2024-49881
     - [ ] CVE-2024-50245
     - [ ] CVE-2024-53058
     - [ ] CVE-2024-49986
     - [ ] CVE-2024-50066
     - [ ] CVE-2024-50101
     - [ ] CVE-2024-50205
     - [ ] CVE-2024-41071
     - [ ] CVE-2024-50038
     - [ ] CVE-2024-50244
     - [ ] CVE-2024-50049
     - [ ] CVE-2024-49863
     - [ ] CVE-2024-50267
     - [ ] CVE-2024-49974
     - [ ] CVE-2024-50055
     - [ ] CVE-2024-53055
     - [ ] CVE-2024-53059
     - [ ] CVE-2024-50176
     - [ ] CVE-2024-50140
     - [ ] CVE-2024-26596
     - [ ] CVE-2024-42129
     - [ ] CVE-2024-50230
     - [ ] CVE-2024-50033
     - [ ] CVE-2024-50130
     - [ ] CVE-2024-50247
     - [ ] CVE-2024-50006
     - [ ] CVE-2024-49975
     - [ ] CVE-2024-49992
     - [ ] CVE-2024-50087
     - [ ] CVE-2024-50194
     - [ ] CVE-2024-49997
     - [ ] CVE-2024-50216
     - [ ] CVE-2024-26785
     - [ ] CVE-2024-49978
     - [ ] CVE-2024-38594
     - [ ] CVE-2024-50145
     - [ ] CVE-2024-50250
     - [ ] CVE-2024-50252
     - [ ] CVE-2024-50031
     - [ ] CVE-2024-50255
     - [ ] CVE-2024-50182
     - [ ] CVE-2024-50268
     - [ ] CVE-2024-49939
     - [ ] CVE-2024-50188
     - [ ] CVE-2024-50139
     - [ ] CVE-2024-50179
     - [ ] CVE-2024-50103
     - [ ] CVE-2024-50246
     - [ ] CVE-2024-53100
     - [ ] CVE-2024-50098
     - [ ] CVE-2024-50010
     - [ ] CVE-2024-50186
     - [ ] CVE-2024-50156
     - [ ] CVE-2024-50044
     - [ ] CVE-2024-50235
     - [ ] CVE-2024-53083
     - [ ] CVE-2024-43868
     - [ ] CVE-2024-50283
     - [ ] CVE-2024-49933
     - [ ] CVE-2024-50279
     - [ ] CVE-2024-50131
     - [ ] CVE-2024-49965
     - [ ] CVE-2024-50005
     - [ ] CVE-2024-50075
     - [ ] CVE-2024-50115
     - [ ] CVE-2024-50202
     - [ ] CVE-2024-50110
     - [ ] CVE-2024-50171
     - [ ] CVE-2024-50150
     - [ ] CVE-2024-50251
     - [ ] CVE-2024-50040
     - [ ] CVE-2024-49870
     - [ ] CVE-2024-49969
     - [ ] CVE-2024-50041
     - [ ] CVE-2024-50200
     - [ ] CVE-2024-50292
     - [ ] CVE-2024-50275
     - [ ] CVE-2024-49954
     - [ ] CVE-2024-50108
     - [ ] CVE-2024-50070
     - [ ] CVE-2024-53101
     - [ ] CVE-2024-49961
     - [ ] CVE-2024-27012
     - [ ] CVE-2024-50272
     - [ ] CVE-2024-50121
     - [ ] CVE-2024-50273
     - [ ] CVE-2024-49935
     - [ ] CVE-2024-49901
     - [ ] CVE-2024-50061
     - [ ] CVE-2024-50153
     - [ ] CVE-2024-49948
     - [ ] CVE-2024-50299
     - [ ] CVE-2024-50003
     - [ ] CVE-2024-53052
     - [ ] CVE-2024-50015
     - [ ] CVE-2024-50229
     - [ ] CVE-2024-50269
     - [ ] CVE-2024-50168
     - [ ] CVE-2024-50240
     - [ ] CVE-2024-49957
     - [ ] CVE-2024-50134
     - [ ] CVE-2024-50239
     - [ ] CVE-2024-50133
     - [ ] CVE-2024-53079
     - [ ] CVE-2024-49976
     - [ ] CVE-2024-50296
     - [ ] CVE-2024-50170
     - [ ] CVE-2024-53063
     - [ ] CVE-2024-49925
     - [ ] CVE-2024-49889
     - [ ] CVE-2024-49947
     - [ ] CVE-2024-50127
     - [ ] CVE-2024-53093
     - [ ] CVE-2024-50058
     - [ ] CVE-2024-43904
     - [ ] CVE-2024-50013
     - [ ] CVE-2024-50285
     - [ ] CVE-2024-49936
     - [ ] CVE-2024-49995
     - [ ] CVE-2024-50298
     - [ ] CVE-2024-53042
     - [ ] CVE-2024-49871
     - [ ] CVE-2024-50096
     - [ ] CVE-2024-49987
     - [ ] CVE-2024-49867
     - [ ] CVE-2024-53068
     - [ ] CVE-2024-36923
     - [ ] CVE-2024-49931
     - [ ] CVE-2024-50073
     - [ ] CVE-2024-50141
     - [ ] CVE-2024-50234
     - [ ] CVE-2024-49930
     - [ ] CVE-2024-49890
     - [ ] CVE-2024-50008
     - [ ] CVE-2024-50125
     - [ ] CVE-2024-50152
     - [ ] CVE-2024-50000
     - [ ] CVE-2024-50062
     - [ ] CVE-2024-50215
     - [ ] CVE-2024-49949
     - [ ] CVE-2024-49973
     - [ ] CVE-2024-50088
     - [ ] CVE-2024-53094
     - [ ] CVE-2024-49926
     - [ ] CVE-2024-50164
     - [ ] CVE-2024-50016
     - [ ] CVE-2024-49996
     - [ ] CVE-2024-50256
     - [ ] CVE-2024-49895
     - [ ] CVE-2024-50048
     - [ ] CVE-2024-49877
     - [ ] CVE-2024-49966
     - [ ] CVE-2024-50099
     - [ ] CVE-2024-47704
     - [ ] CVE-2024-49937
     - [ ] CVE-2024-50271
     - [ ] CVE-2024-49955
     - [ ] CVE-2024-50184
     - [ ] CVE-2024-49927
     - [ ] CVE-2024-50169
     - [ ] CVE-2024-50284
     - [ ] CVE-2024-49959
     - [ ] CVE-2024-53072
     - [ ] CVE-2024-49905
     - [ ] CVE-2024-50294
     - [ ] CVE-2024-50261
     - [ ] CVE-2024-50249
     - [ ] CVE-2024-49878
     - [ ] CVE-2024-50076
     - [ ] CVE-2024-50286
     - [ ] CVE-2024-50221
     - [ ] CVE-2024-50264
     - [ ] CVE-2024-49960
     - [ ] CVE-2024-50192
     - [ ] CVE-2024-50120
     - [ ] CVE-2024-53066

   - [ ] expat `2.5.0` → `2.6.4` 
     - [ ]  CVE-2024-45490
   - [ ] python3-setuptools `68.1.2` → `74.1.2`
     - [ ] CVE-2024-6345 
   - [ ] containerd,  rebuild without the vulnerable `x-net` 
     - [ ] CVE-2023-45288
   - [ ] google-guest-agent  `20211116.00-6.2` → `20241122.02`
     - [ ] CVE-2024-24790 
     - [ ] CVE-2023-45283 
     - [ ] CVE-2023-45288
     - [ ] CVE-2024-24784
     - [ ] CVE-2023-45290
     - [ ] CVE-2024-24788
     - [ ] CVE-2024-24783
  - [ ] libpcap `1.10.4` → `1.10.5`
    - [ ] CVE-2023-40400
    - [ ] CVE-2024-8006
    - [ ] CVE-2023-7256
  - [ ] less `590-2` → `643-1`
    - [ ] CVE-2022-46663  
   - [ ] curl `8.5.0-2` → `8.11.0-1`
     - [ ] CVE-2024-8096
     - [ ] CVE-2024-7264
     - [ ] CVE-2024-9681
     - [ ] CVE-2024-6197
     - [ ] CVE-2024-6874

- [ ] Complete the build (stage 1)
- [ ] Complete the publishing (stage 2)
- [ ] Publish the release note
- [ ] Inform Gardener team the patch is ready.

**Comment by pnpavlov** [comment]
must be done before 1.12.24
