### ISSUE TITLE
CIS Feature: Replace Tripwire

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#782]
**Background**:
PR #771 added the first iteration of the new `CIS` feature to Garden Linux. However, this feature is still declared as `WIP` and needs to be adjusted to fulfill all requirements of #647.

**Task**:
Filesystem integrity checking must be added and included by the `CIS` feature. While the default leads to `Tripwire` we need to evaluate and find an alternative that doesn't depends on `libdb` (BerkleyDB). Next to this, we need to whitelist the current checks and recreate equal ones for the new solution.

- [x] Find alternative solution (not depending on `libdb`)
- [x] Integrate and test solution
- [x] Whitelist test id `1.4.1_install_tripwire`
- [x] Whiteliste test id `1.4.2_tripwire_cron`
- [x] Create equal tests for new solution

**Comment by gyptazy** [comment]
Hi @chrinorse,

while testing my new CIS enhancements I saw this check failing:
```
1.4.4_aide_cron           [ KO ] aide --check is not present in /etc/crontab /etc/cron.d/sysstat
/etc/cron.d/.placeholder
1.4.4_aide_cron           [ KO ] Check Failed
```

Please take a short look in to this.

Thanks,
gyptazy
