### ISSUE TITLE
macOS: General Support (Meta)

### ISSUE THREAD

**Issue by gyptazy** [gardenlinux/gardenlinux#989]
**Task**:
We should test and validate the possibilities to build Garden Linux on macOS (amd64 + arm64). This was requested by @gehoern in #957.

Can you also take a look if the whole build process will run on an apple at all (maybe separate issue)?

_Originally posted by @gehoern in https://github.com/gardenlinux/gardenlinux/issues/957#issuecomment-1144799262_

**Tasks**:
- [x] Identify needed Adjustments
- [x] Adjust Build Pipeline
- [x] CRE Support (Podman or Docker)
- [x] Build Support on macOS with Apple AMD64
- [x] Build Support on macOS with Apple Silicon (ARM64)
- [ ] Support for additional tool: `garden-feat` #1024
- [ ] Support for additional tool: #1021
- [ ] Support for PyTests: #1022

**Comment by gyptazy** [comment]
# Tasks

## Podman
`Podman` seems not to be the best solution for macOS since we can only interact remotely with other instances (https://github.com/containers/podman/issues/4364). Therefore, we need to evaluate the optional Docker support.

## GNU Tools
Many tools used within the build pipeline use GNU versions and are not directly compatible with the Unix style. This affects `grep`, `awk`, `date`, `bash`, `make`. Many of them can be obtained via `Homebrew` but they won't take the default place. As a result, the scripts must be adjusted to use the `GNU` ones, when a `Darwin` based OS type (e.g. `name -s`) is detected. This results in may changes regarding the build pipeline before the container part is reached.

## POSIX
Not everything is full posix conform and needs to be adjusted or bash aligned and may take some time.

## Make
We need to adjust the Makefiles to use a newer GNU version of make. This may be obsolete or handled in another way but needs some further testing.

**Comment by gyptazy** [comment]
Pure building of Garden Linux images is now supported within the linked PR for macOS with Apple AMD64 and ARM64 (Apple Silicon). However, still some adjustments are needed for additional tool sets.
